### PR TITLE
Fix/mo2 support

### PR DESCRIPTION
**Pull request by rfuzzo**
some way towards MO2 support
- works for reading and getting files
- there is an issue present where creating new files at runtime sometimes fails to be registered, a game restart fixes this however

### CODE REVIEW

**Comment by poirierlouis** [comment]
Thanks, I have an idea I'll try to get the root folder of MO2.

**Comment by poirierlouis** [comment]
FYI, I can get the root directory of MO2, but its only `<MO2>\overwrite\...` to write files, while reading is in `<MO2>\mods\[ModName]\...`.

**Comment by rfuzzo** [comment]
it's weird... I spent some time debugging it today
Some scenarios:
1. `overwrite/r6/storage/HUDPainter` folder does NOT exist on game start -> mod can save files, but then cannot read the newly created file
2. `overwrite/r6/storage/HUDPainter` folder does exist  on game start -> mod can save and read files
3. `overwrite/r6/storage/HUDPainter` folder does NOT exist on game start but is created on game load-> mod can save files, but then can NOT read the newly created files

for some reason, `std::directory_iterator` doesn't recognize the folder as existing when it is not presen on game start

I suspect it is because the VFS of MO2 maps all directory layers only ONCE on dll load
and for some reason, it doesn't add a new mapping when a folder is created after UVFS has already been attached
mappings we need are:
- `<GAME>/r6/storage/HUDPainter`
- `<MO2>/mods/HUD Painter/r6/storage/HUDPainter`
- `<MO2>/overwrite/r6/storage/HUDPainter`

**Comment by poirierlouis** [comment]
Thanks for your tests!

Weird thing is that, if I try without `create_directories`. Logs shows no error when using STL, like to create HUDPainter directory with `get_storage`. But directory is never created, not in `overwrite` nor in `game`.

You tested (1), (2) and (3) with current state of this PR or you have more local changes? I assume you don't create directory manually, only using a relaunch?

I'll test with `create_directories` on my side to see if it is replicable.

**Comment by poirierlouis** [comment]
Thanks for your feedback 🙂.

I found the culprit when listing files. It should be using [entry.path()](https://github.com/rayshader/cp2077-red-filesystem/blob/1fd405e042d37e12399f207fcc2e01afc8e68205/src/FileSystemStorage.cpp#L85) only instead of re-creating the path.

MO2 is looking into `weakly_canonical`.

**Comment by rfuzzo** [comment]
oh? does it work now?

**Comment by rfuzzo** [comment]
> Thanks for your feedback 🙂.
> 
> I found the culprit when listing files. It should be using [entry.path()](https://github.com/rayshader/cp2077-red-filesystem/blob/1fd405e042d37e12399f207fcc2e01afc8e68205/src/FileSystemStorage.cpp#L85) only instead of re-creating the path.
> 
> MO2 is looking into `weakly_canonical`.

Doesn't make a difference...

**Comment by poirierlouis** [comment]
Thanks!
Fixed with a3a9cd53ba30131215a50126161cad67e266ee0a.

**Pull request closed without merging**
